SELECT * FROM [USER]
SELECT * FROM PEGAWAI
SELECT * FROM MEMBER
SELECT * FROM EMAIL_USER

-- Delete rows from table 'TableName'
DELETE FROM [USER]
GO

SELECT EMAIL_USER.AlamatEmail, [USER].UserPassword  
FROM [USER]
INNER JOIN EMAIL_USER
ON [USER].IDUser = EMAIL_USER.IDUser
